######################################################################
#Python Script Generated by GeneratePythonScript Algorithm
######################################################################
Load(Filename=r'/SNS/CORELLI/IPTS-12008/nexus/CORELLI_306.nxs.h5',OutputWorkspace='CORELLI_306',LoadMonitors='1',MonitorsAsEvents='1')
Load(Filename=r'/SNS/CORELLI/IPTS-12008/nexus/CORELLI_317.nxs.h5',OutputWorkspace='CORELLI_317',LoadMonitors='1',MonitorsAsEvents='1')
ScaleX(InputWorkspace='CORELLI_317_monitors',OutputWorkspace='CORELLI_317_monitors',Factor='0.997')
ScaleX(InputWorkspace='CORELLI_306_monitors',OutputWorkspace='CORELLI_306_monitors',Factor='0.997')
Rebin(InputWorkspace='CORELLI_317_monitors',OutputWorkspace='CORELLI_317_monitors',Params='5')
Rebin(InputWorkspace='CORELLI_306_monitors',OutputWorkspace='CORELLI_306_monitors',Params='5')
Divide(LHSWorkspace='CORELLI_317_monitors',RHSWorkspace='CORELLI_306_monitors',OutputWorkspace='out',WarnOnZeroDivide='0')
