######################################################################
#Python Script Generated by GeneratePythonScript Algorithm
######################################################################
StartLiveData(UpdateEvery='10',Instrument='CORELLI',StartTime='1990-01-01T00:00:00',ProcessingScript='Rebin(InputWorkspace=input,OutputWorkspace=output,Params='0,10,17000')
SumSpectra(InputWorkspace=output,OutputWorkspace=output)
',OutputWorkspace='live')
