######################################################################
#Python Script Generated by GeneratePythonScript Algorithm
######################################################################
from mantid.simpleapi import *

